apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: helloworldweb
        image: netcol19.azurecr.io/helloworldweb
        ports:
        - containerPort: 80
