services:
  run:
    build:
      context: .
      target: run
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ShareForFuture;User=sa;Password=P@ssw0rd!123
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    depends_on:
      - db
    links:
      - db
    ports:
      - 8081:80
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!123
      - MSSQL_PID=Express
